---

sudo: false

language: python

env:
  global:
    COVERALLS_PARALLEL=true
    NOSE=nosetests

matrix:
  fast_finish: true
  include:
    - name: "2.7 Linux"
      env: BUILD=test FORCE_TTY=Y
      python: '2.7'
    - name: "3.5 Linux"
      env: BUILD=test FORCE_TTY=Y
      python: '3.5'
    - name: "3.6 Linux"
      env: BUILD=test FORCE_TTY=Y
      python: '3.6'
    - name: "3.7 Linux"
      env: BUILD=test FORCE_TTY=Y
      python: '3.7'
    - name: "pypy Linux"
      env: BUILD=test FORCE_TTY=Y
      python: 'pypy'
    - name: "3.8 Windows"
      os: windows
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
         - choco install python --version 3.8.0
         - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH BUILD=test FORCE_TTY=Y NOSE="cmd /C nosetests"

    - env: BUILD=docs
      python: '3.6'

install:
  - pip install -r requirements/dev.txt

script:
  - |
    set -ex
    case "$BUILD" in
      test)
        $NOSE --with-coverage --cover-package=asciimatics
        ;;
      docs)
        cd doc && cp source/conf_orig.py source/conf.py && ./build.sh
        ;;
    esac
    set +ex

after_success:
  - |
    set -ex
    case "$BUILD" in
      test)
        coveralls
        ;;
    esac
    set +ex

notifications:
  webhooks: https://coveralls.io/webhook
